### ISSUE TITLE
Null ref in ICSharpCode.AvalonEdit.Editing.TextAreaAutomationPeer.GetPattern

### ISSUE THREAD

**Issue by MillerMark** [icsharpcode/AvalonEdit#240]
I'm using AvalonEdit and trying to implement code completion. As I enter characters in the editor that trigger the completion window, often I will suddenly get a null ref with the following stack trace (my code is nowhere in the trace):

   at ICSharpCode.AvalonEdit.Editing.TextAreaAutomationPeer.GetPattern(PatternInterface patternInterface)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.Automation.UIElementAutomationObject.GetProvider[ProviderWrapperT,ProviderT](UIElement element, DependencyProperty providerDependencyProperty, PatternInterface patternInterface, Func`3 providerFactory)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.Automation.UIElementAutomationObject.GetScrollProvider(UIElement element)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.LoadSupportedAutomationPeerPatternProperties(UIElement element)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.InitializeAccessibilityProperties(Int64 instanceHandle, Object targetObject)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.InitializePropertyAndSourceCaches(Int64 instanceHandle, Object targetObject)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.GetPropertyValuesChainInternal(Int64 instanceHandle, Object targetObject)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.<>c__DisplayClass30_0.<GetPropertyValuesChainInternal>b__0()
   at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.GetPropertyValuesChainInternal(Int64 instanceHandle, Object targetObject)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.Properties.PropertyService.HandlePropertyChainRequest(PropertiesRequestInfo requestInfo)
   at Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.HandleMessage[TMessage,TReply](Func`2 callback, Message request)
   at Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.<>c__DisplayClass27_0`2.<RegisterMessageObserver>b__0(Message message)
   at Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.ProcessInboundMessage(Message message)
   at Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.<>c__DisplayClass40_0.<OnMessageReceived>b__0()
   at Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.WaitableActionsList.<>c__DisplayClass8_0.<AddAndSignal>b__0(Boolean isCancelled)
   at Microsoft.VisualStudio.DesignTools.WpfTap.Networking.ProtocolHandler.ActionThread(Object list)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by jimfoye** [comment]
Hello Señor Coderush! Perhaps this is your problem?

https://developercommunity.visualstudio.com/content/problem/1055570/an-unhandled-exception-of-type-systemnullreference-1.html

Which was fixed in Visual Studio 2019 version 16.6.2.

**Comment by MillerMark** [comment]
Hi @jimfoye - thanks for the quick response. That seems to be exactly my problem. After updating to 16.6.2, I can no longer reproduce.
